### ISSUE TITLE
Cannot read property 'user' of undefined

### ISSUE THREAD

**Issue by bibi-blocksberg** [Kneckter/DiscordRoleBot#3]
hello
i always have this mistake

do not know why
he meets with pm2

**Comment by Kneckter** [comment]
This isn't related to pm2. Do you have a user in your database that isn't in your server?

Did you run `npm install` to get the latest modules from the last update?

Can you post the full error if you still get it after that? It's not really helpful to just state the description. The traceback is really helpful

**Comment by bibi-blocksberg** [comment]
I think 1 user is no longer on the server

npm is new

The only thing I took because of pm2 was the sql from the main folder, otherwise the bot restarts every 2 seconds under pm2


only have this
https://gyazo.com/9efbe0c94684ff2045fcc955b434014e

**Comment by Kneckter** [comment]
Was the bot working for you before or is this the first time you are setting it up?

Does the bot have the correct permissions on your server? Note that Discord changed their developer portal to have toggles for bots that read the server uses. You'll need to enable those options now.

I don't understand what you mean about the sql. Can you elaborate? There isn't sql in the folder so your comment confuses me.

For pm2, you can use the `pm2 log` command to see the logs from the bot. I've never used the interface like you showed it

**Comment by bibi-blocksberg** [comment]
I have now deleted a user who I know is no longer on the discord server
is there a possibility that the bot doesn't crash every time

I certainly didn't notice that before because it ran forever



then i noticed that users were stored in the database where the time had run out but they had not been removed from their role
not even after a manual check

**Comment by Kneckter** [comment]
Are you running the latest version of the bot? Run `git pull` to see if it pulls any update and `git log -2` to see what is the latest commit you are on. It should be the commit from Oct 7th. It shouldn't crash when a person leaves your server, i added a check on the query for that a few commits ago.

You ever get a chance to get the full error message from pm2? You could probably click on the error title to get more info but `pm2 log` would give you the output of the bot.

Seeing users in the DB that had run out of time but didn't have their role removed sounds like you are on an older version of the bot.

**Comment by bibi-blocksberg** [comment]
1|DiscordRoleBot       | TypeError: Cannot read property 'user' of undefined
1|DiscordRoleBot       |     at Statement.sql.all (/home/bots/Discordrolebot/adminBot.js:55:32)
1|DiscordRoleBot       | TypeError: Cannot read property 'user' of undefined
1|DiscordRoleBot       |     at Statement.sql.all (/home/bots/Discordrolebot/adminBot.js:55:32) '[11/19/2020, 3:20:01 AM] Uncaught Exception thrown'
PM2                    | App name:DiscordRoleBot id:1 disconnected
PM2                    | App [DiscordRoleBot:1] exited with code [1] via signal [SIGINT]
PM2                    | App [DiscordRoleBot:1] starting in -cluster mode-
PM2                    | App [DiscordRoleBot:1] online
1|DiscordRoleBot       | [11/19/2020, 3:20:02 AM] -- DISCORD ROLE BOT IS READY --
1|DiscordRoleBot       | TypeError: Cannot read property 'user' of undefined
1|DiscordRoleBot       |     at Statement.sql.all (/home/bots/Discordrolebot/adminBot.js:55:32)
1|DiscordRoleBot       | TypeError: Cannot read property 'user' of undefined
1|DiscordRoleBot       |     at Statement.sql.all (/home/bots/Discordrolebot/adminBot.js:55:32) '[11/19/2020, 3:30:01 AM] Uncaught Exception thrown'
PM2                    | App name:DiscordRoleBot id:1 disconnected
PM2                    | App [DiscordRoleBot:1] exited with code [1] via signal [SIGINT]
PM2                    | App [DiscordRoleBot:1] starting in -cluster mode-
PM2                    | App [DiscordRoleBot:1] online
1|DiscordRoleBot       | [11/19/2020, 3:30:02 AM] -- DISCORD ROLE BOT IS READY --
1|DiscordRoleBot       | TypeError: Cannot read property 'user' of undefined
1|DiscordRoleBot       |     at Statement.sql.all (/home/bots/Discordrolebot/adminBot.js:55:32)
1|DiscordRoleBot       | TypeError: Cannot read property 'user' of undefined
1|DiscordRoleBot       |     at Statement.sql.all (/home/bots/Discordrolebot/adminBot.js:55:32) '[11/19/2020, 3:40:01 AM] Uncaught Exception thrown'
PM2                    | App name:DiscordRoleBot id:1 disconnected
PM2                    | App [DiscordRoleBot:1] exited with code [1] via signal [SIGINT]
PM2                    | App [DiscordRoleBot:1] starting in -cluster mode-
PM2                    | App [DiscordRoleBot:1] online
1|DiscordRoleBot       | [11/19/2020, 3:40:02 AM] -- DISCORD ROLE BOT IS READY --

**Comment by Kneckter** [comment]
I see that it failed to create the user entry on line 55. I added a try/catch to report if a user has left the server. I chose not to have the bot remove the entry because Discord could go down and the bot would think all users left your server (it has happened to me before). Instead, it will report the ID to the main channel.

This would have stopped the bot from removing roles and deleting records but the new error handling should let it process the whole list if someone leaves.

Do a `git pull` to get the update and let me know if you run into any errors.

**Comment by bibi-blocksberg** [comment]
thanks, I'll do that


only my question would be:

if a user leaves the server and joins again, the bot could automatically give him the role again or

and a function for lifetime role

then the bot could permanently check the role and compare it with the database

Of course you would have to define beforehand in the config which role the bot can give and take


i have been using the bot for a few months and i have to say that the bot has worked

do not know any comparable opensource

**Comment by Kneckter** [comment]
The bot currently does not reapply the role if someone leaves and rejoins. The bot will simply remove them from the DB if they rejoin because it only cares about that user if they are under the 5 day limit. Adding the code to reapply the role is a big change since there's no check like that right now. I don't think it would even be too useful since a person would leave the server for a reason and if they came back, they should have to explain it to the admin. I've ran this bot for 2 years with 300 members and that situation never happened.

**Comment by bibi-blocksberg** [comment]
git pull doesn't work because i downloaded the data via zip ... but now i have taken the repo directly via the server with gitclone



for me the case was already 2 times

but only one idea was good =)

**Comment by bibi-blocksberg** [comment]
new error
https://gyazo.com/e8ea41ba2321bf6c90a3d0e052d38bd4


4|DiscordRoleBot  | [11/19/2020, 7:21:01 AM] Failed to find a user for ID: 459662864303521802. They may have left the server.
4|DiscordRoleBot  | [11/19/2020, 7:21:01 AM] Failed to find a user for ID: 368444330639360000. They may have left the server.
4|DiscordRoleBot  | [11/19/2020, 7:21:01 AM] Failed to find a user for ID: 282086204608872449. They may have left the server.
4|DiscordRoleBot  | [11/19/2020, 7:21:01 AM] Failed to find a user for ID: 475900488639053824. They may have left the server.
4|DiscordRoleBot  | [11/19/2020, 7:21:01 AM] Failed to find a user for ID: 397682726138019840. They may have left the server.
4|DiscordRoleBot  | [11/19/2020, 7:21:01 AM] Failed to find a user for ID: 637606234979303434. They may have left the server.
4|DiscordRoleBot  | [11/19/2020, 7:21:01 AM] Failed to find a user for ID: 542459157178089541. They may have left the server.
4|DiscordRoleBot  | [11/19/2020, 7:21:01 AM] Failed to find a user for ID: 468087989113978882. They may have left the server.
4|DiscordRoleBot  | [11/19/2020, 7:21:01 AM] Failed to find a user for ID: 537294452025458688. They may have left the server.
4|DiscordRoleBot  | [11/19/2020, 7:21:01 AM] Failed to find a user for ID: 667403754613506058. They may have left the server.
4|DiscordRoleBot  | [11/19/2020, 7:21:01 AM] Failed to find a user for ID: 351391412484571139. They may have left the server.
4|DiscordRoleBot  | [11/19/2020, 7:21:01 AM] Failed to find a user for ID: 226781668252319746. They may have left the server.
4|DiscordRoleBot  | TypeError: bot.guilds.get is not a function
4|DiscordRoleBot  |     at Statement.sql.all (/home/bots/DiscordRoleBot/adminBot.js:120:49)
4|DiscordRoleBot  | TypeError: bot.guilds.get is not a function
4|DiscordRoleBot  |     at Statement.sql.all (/home/bots/DiscordRoleBot/adminBot.js:120:49) '[11/19/2020, 7:21:01 AM] Uncaught Exception thrown'
PM2               | App name:DiscordRoleBot id:4 disconnected
PM2               | App [DiscordRoleBot:4] exited with code [1] via signal [SIGINT]
PM2               | App [DiscordRoleBot:4] starting in -cluster mode-
PM2               | App [DiscordRoleBot:4] online
4|DiscordRoleBot  | [11/19/2020, 7:21:02 AM] -- DISCORD ROLE BOT IS READY --


on the server 
282086204608872449
542459157178089541
537294452025458688
351391412484571139
226781668252319746




not on the server 
459662864303521802
368444330639360000
475900488639053824
397682726138019840
637606234979303434
468087989113978882
667403754613506058

**Comment by bibi-blocksberg** [comment]
https://gyazo.com/770b9a20da52b818bcfe3336c7232511

226781668252319746


These are expired VIP roles that are still stored in the database and have not been deleted and the role has not been removed from the users

**Comment by Kneckter** [comment]
I pushed a correction for `TypeError: bot.guilds.get is not a function`. It was from upgrading to v12 of the library. Do a `git pull && npm install` to get the update.

If `226781668252319746` is on the server and the bot cannot find their username, it will most likely be because Discord changed the bot portal to block bots from caching the user list by default. Go to https://discord.com/developers/applications, click on the bot's icon, click on `Bot` on the left, and enable `PRESENCE INTENT` and `SERVER MEMBERS INTENT`. Let me know if it gets those users for you. I'll add this info to the readme.
