### ISSUE TITLE
Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.

### ISSUE THREAD

**Issue by svenberg** [Kneckter/DiscordRoleBot#32]
I keep getting these each cycle of check:

```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.
    at Timeout._onTimeout (/root/bots/DiscordRoleBot/node_modules/discord.js/src/managers/GuildMemberManager.js:454:16)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7)
[9/6/2024, 1:04:42 AM] Unhandled Rejection at Promise:  Promise {
  <rejected> Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.
      at Timeout._onTimeout (/root/bots/DiscordRoleBot/node_modules/discord.js/src/managers/GuildMemberManager.js:454:16)
      at listOnTimeout (node:internal/timers:581:17)
      at process.processTimers (node:internal/timers:519:7) {
    [Symbol(code)]: 'GUILD_MEMBERS_TIMEOUT'
  }
}
```

What I have done:
Pulled latest master on new server, npm install.
Move database from one server to another, same where I now run the bot.
The bot worked well on the other server, I use the same Discord bot so the Intents are unchanged since years.

I looked a bit into node versions if that could be the reason, but I get the same issue for all these node versions:
- 16.14.2: as stated needed in readme
- 18.16.1: this is what i ran on my other server
- 20.17.0: this is my default on the server

When launching the bot I get:
```
[9/6/2024, 12:51:06 AM] -- DISCORD ROLE BOT IS READY --
[9/6/2024, 12:51:06 AM] Connected to SQL!
[9/6/2024, 12:51:06 AM] [InitDB] DB version: 5, Latest: 5
```
and if I type in my configured command channel these are working as well (tried checking, adding, removing a role)

The only significant change made is I moved from mysql to mariadb, but I doubt that's the issue here as the init launch is OK?

**Comment by ReuschelCGN** [comment]
@svenberg Hey did you find a solution? Problem start here also, changed nothing since years....
